"""add card model

Revision ID: 085071771ff4
Revises: de3dc425399d
Create Date: 2022-06-28 11:18:18.487586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '085071771ff4'
down_revision = 'de3dc425399d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('card_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('card_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    # ### end Alembic commands ###
