"""changing defaultPos to pOSx and PosY

Revision ID: 10868b31c35a
Revises: bd22f391d3b1
Create Date: 2022-07-17 22:18:59.028239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10868b31c35a'
down_revision = 'bd22f391d3b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('PosX', sa.Integer(), nullable=True))
    op.add_column('card', sa.Column('PosY', sa.Integer(), nullable=True))
    op.drop_column('card', 'defaultPos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('defaultPos', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('card', 'PosY')
    op.drop_column('card', 'PosX')
    # ### end Alembic commands ###
