"""empty message

Revision ID: 1c74285a64e7
Revises: 9fa7a8828363
Create Date: 2022-06-28 11:04:42.136986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c74285a64e7'
down_revision = '9fa7a8828363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('card_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'board', 'board', ['card_id'], ['board_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'board', type_='foreignkey')
    op.drop_column('board', 'card_id')
    # ### end Alembic commands ###
