"""empty message

Revision ID: 26515f7cdd6d
Revises: d96b1b833f1e
Create Date: 2022-07-19 15:01:40.170824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26515f7cdd6d'
down_revision = 'd96b1b833f1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('color', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'color')
    # ### end Alembic commands ###
