"""changed likes_count in Card to nullable

Revision ID: 335b1eba02b7
Revises: 992db42cb27c
Create Date: 2022-07-02 07:24:45.391819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '335b1eba02b7'
down_revision = '992db42cb27c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'likes_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'likes_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
