"""empty message

Revision ID: 430f1735e9c9
Revises: 3b9429e44916
Create Date: 2022-07-21 21:15:54.294247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430f1735e9c9'
down_revision = '3b9429e44916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('theme', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'theme')
    # ### end Alembic commands ###
