"""skw: add foreign board key to cards, establish board-card relationship

Revision ID: 43c93b74e459
Revises: 3d79542175f6
Create Date: 2022-06-28 11:12:49.396989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43c93b74e459'
down_revision = '3d79542175f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('board_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cards', 'boards', ['board_id'], ['board_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_column('cards', 'board_id')
    # ### end Alembic commands ###
