"""Added foreign key to Card model

Revision ID: 577622fb4428
Revises: d01573c720c0
Create Date: 2022-06-27 15:54:32.755068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577622fb4428'
down_revision = 'd01573c720c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('board_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'card', 'board', ['board_id'], ['board_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'board_id')
    # ### end Alembic commands ###
