"""set messaage nullable=False

Revision ID: 762b62826263
Revises: 0bffa034602e
Create Date: 2022-06-29 14:42:46.316003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762b62826263'
down_revision = '0bffa034602e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
