"""nested card in board

Revision ID: 787e6838b56c
Revises: 085071771ff4
Create Date: 2022-06-28 11:47:25.955598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787e6838b56c'
down_revision = '085071771ff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('board_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'card', 'board', ['board_id'], ['board_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'board_id')
    # ### end Alembic commands ###
