"""created a one-to-many relationship between board and cards

Revision ID: 992db42cb27c
Revises: c8361f96db2c
Create Date: 2022-07-02 04:01:12.420122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '992db42cb27c'
down_revision = 'c8361f96db2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('board_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'card', 'board', ['board_id'], ['board_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'board_id')
    # ### end Alembic commands ###
