"""empty message

Revision ID: 9e7342f3349b
Revises: 1c74285a64e7
Create Date: 2022-06-28 20:00:00.610896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e7342f3349b'
down_revision = '1c74285a64e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('board_card_id_fkey', 'board', type_='foreignkey')
    op.drop_column('board', 'card_id')
    op.add_column('card', sa.Column('board_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'card', 'board', ['board_id'], ['board_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'board_id')
    op.add_column('board', sa.Column('card_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('board_card_id_fkey', 'board', 'board', ['card_id'], ['board_id'])
    # ### end Alembic commands ###
