"""empty message

Revision ID: 9f2c9145713d
Revises: 335b1eba02b7
Create Date: 2022-07-21 13:02:22.282106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f2c9145713d'
down_revision = '335b1eba02b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'board_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'board_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
